apiVersion: v1
kind: Service
metadata:
  name: blog-service
  labels:
    name: blog-service
    app: blog-app
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30004
  selector:
    name: blog-app-pod
    app: blog-app
